alertmanager:
  persistentVolume:
    enabled: false
server:
  nodeSelector: {}
  affinity: {}
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  persistentVolume:
    enabled: false
  config:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'abc-deploy'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_label_prometheus_io_path]
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__meta_kubernetes_pod_label_prometheus_io_port, __address__]
            regex: (.+);(.+):.*
            replacement: $2:$1
            target_label: __address__
            action: replace
